import Category from '@/components/Category'
import Food from '@/components/Food'
import HeadlineCards from '@/components/HeadlineCards'
import Hero from '@/components/Hero'
import Navbar from '@/components/Navbar'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Hero/>
      <HeadlineCards/>
      <Food/>
      <Category/>
      
      
    </>
  )
}
